---
kind: pipeline
name: build-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: always
  image: spritsail/docker-build
  settings:
    make: true

- name: test-bin
  pull: always
  image: spritsail/docker-test
  settings:
    run: |
      busybox && \
      curl --version && \
      xmlstarlet --version

- name: test
  pull: always
  image: spritsail/docker-test
  settings:
    curl: :32400/identity
    delay: 5
    pipe: |
      xmlstarlet sel -t -v "/MediaContainer/@version" |
      grep -qw "$(label io.spritsail.version.plex | cut -d- -f1)"
    retry: 10

- name: publish
  pull: always
  image: spritsail/docker-publish
  settings:
    repo: spritsail/plex-media-server
    tags:
    - plexpass
    - "%label io.spritsail.version.plex | %prefix plexpass | %remsuf [0-9a-f]+$ | %auto 2"
    login: {from_secret: docker_login}
  when:
    branch:
    - pass
    event:
    - push
---
kind: signature
hmac: a6e529b62ed2ecf24b2c3125f7267c321d56ce16d1cd8178f96e0399dd3096bd

...
