---
kind: pipeline
name: build-nvidia-amd64

platform:
  os: linux
  arch: amd64

#depends_on:
#- build-amd64

steps:
- name: build
  pull: always
  image: spritsail/docker-build
  settings:
    dockerfile: Dockerfile.nvidia
    make: true

- name: publish
  pull: always
  image: spritsail/docker-publish
  settings:
    repo: spritsail/plex-media-server
    tags:
    - plexpass-nvidia
    - "%label io.spritsail.version.plex | %prefix plexpass-nvidia | %remsuf [0-9a-f]+$ | %auto 2"
    login: {from_secret: docker_login}
  when:
    branch:
    - nvidia
    event:
    - push

---
kind: signature
hmac: d7799de75f1932b1aa3757273cad30c30d56442175e1ca2714720b252f6d7398

...
