---
kind: pipeline
name: build-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: always
  image: spritsail/docker-build
  settings:
    make: true
    repo: ppass-dev

- name: test-bin
  pull: always
  image: spritsail/docker-test
  settings:
    repo: ppass-dev
    run: |
      curl --version &&
      xmlstarlet --version

- name: test
  pull: always
  image: spritsail/docker-test
  settings:
    curl: :32400/identity
    delay: 5
    pipe: |
      xmlstarlet sel -t -v "/MediaContainer/@version" |
      grep -qw "$(label io.spritsail.version.plex | cut -d- -f1)"
    repo: ppass-dev
    retry: 10

- name: publish
  pull: always
  image: spritsail/docker-publish
  settings:
    from: ppass-dev
    repo: spritsail/plex-media-server
    tags:
    - plexpass
    - "%label io.spritsail.version.plex | %prefix plexpass | %remsuf [0-9a-f]+$ | %auto 2"
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    branch:
    - pass
    event:
    - push

---
kind: signature
hmac: 9ccac4af6a5a1f3849f3593741c44df1564956093fc038f628fa500973969b43

...
