---
kind: pipeline
name: build-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: always
  image: spritsail/docker-build
  settings:
    make: true
    repo: plex-dev

- name: test-bin
  pull: always
  image: spritsail/docker-test
  settings:
    repo: plex-dev
    run: |
      curl --version &&
      xmlstarlet --version

- name: test
  pull: always
  image: spritsail/docker-test
  settings:
    curl: :32400/identity
    delay: 5
    pipe: |
      xmlstarlet sel -t -v "/MediaContainer/@version" |
      grep -qw "$(label io.spritsail.version.plex | cut -d- -f1)"
    repo: plex-dev
    retry: 10

- name: publish
  pull: always
  image: spritsail/docker-publish
  settings:
    from: plex-dev
    repo: spritsail/plex-media-server
    tags:
    - latest
    - "%label io.spritsail.version.plex | %remsuf [0-9a-f]+$ | %auto 2"
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    branch:
    - master
    event:
    - push

---
kind: signature
hmac: c1c9e7fe83806aba030d7395e11d9077863538131d04c8c291600fe8c84b99bc

...
